/*
 * BshLoaderFrame.java
 *
 * Copyright (C) 2008-2012 M. Litherland
 */

package org.nule.integrateclient.extra;

import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author  mike
 */
public class BshLoaderFrame extends javax.swing.JFrame {
    
    private BshLogicForm logicForm;
    
    private Map templates = new TreeMap();
    private String currentLogic = "";
    
    /** Creates new form BshLoaderFrame */
    public BshLoaderFrame(BshLogicForm logicForm) {
        initComponents();
        this.logicForm = logicForm;
        setTitle("Select script template");
        String init = "Passthrough Logic - default.bsh";
        templates.put(init, 
                "/org/nule/integrateclient/samples/bsh/default.bsh");
        templates.put("HL7 Anon Logic - hl7anon.bsh", 
                "/org/nule/integrateclient/samples/bsh/hl7anon.bsh");
        templates.put("Manual Pause - manualpause.bsh", 
                "/org/nule/integrateclient/samples/bsh/manualpause.bsh");
        templates.put("Create HL7 from MRNs - createhl7frommrns.bsh", 
                "/org/nule/integrateclient/samples/bsh/createhl7frommrns.bsh");
        templates.put("Minimal Logic - minimal.bsh", 
                "/org/nule/integrateclient/samples/bsh/minimal.bsh");
        templates.put("Simple Map Logic - simplemap.bsh", 
                "/org/nule/integrateclient/samples/bsh/simplemap.bsh");
        templates.put("Slowdown Logic - slowdown.bsh", 
                "/org/nule/integrateclient/samples/bsh/slowdown.bsh");
        templates.put("Init Example Logic - slowdowninit.bsh", 
                "/org/nule/integrateclient/samples/bsh/slowdowninit.bsh");
        templates.put("Database Example Logic - classpath.bsh", 
                "/org/nule/integrateclient/samples/bsh/classpath.bsh");
        jComboBox1.setModel(new DefaultComboBoxModel(templates.keySet().toArray()));
        jComboBox1.getModel().setSelectedItem(init);
        setCurrent(init);
        setLocation(Positioner.getX(), Positioner.getY());
        setVisible(true);
    }
    
    private void setCurrent(String selected) {
        BufferedReader br = null;
        try {
            InputStream resource = BshLoaderFrame.class.
                    getResourceAsStream((String) templates.get(selected));
            br = new BufferedReader(new InputStreamReader(resource));
            StringBuilder sb = new StringBuilder();
            StringBuilder desc = new StringBuilder();
            String line = br.readLine();
            while (line != null) {
                sb.append(line).append("\n");
                if (line.startsWith("// DESC: ")) {
                    desc.append(line.substring(9)).append(" ");
                }
                line = br.readLine();
            }
            currentLogic = sb.toString();
            jTextArea1.setText(desc.toString());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error opening resource: "+e);
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {}
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select a script template to load");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jComboBox1, 0, 437, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String selected = (String) jComboBox1.getSelectedItem();
    setCurrent(selected);
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    logicForm.setEditor(currentLogic);
    dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
